#output the number of points generated by a LaserScan
#quick and dirty solution, not meant to be long-term
#Dmitri Smith, 2021

import sys

def main():
    if len(sys.argv) != 2:
        print("Error: Only takes 2 arguments. \nCorrect format: point_counter.py [LaserScan output].txt")
        quit()
    file_name = sys.argv[1]
    if file_name[-4::] != '.txt':
        print('Must be .txt file, found \'{}\''.format(file_name[-4::]))
        quit()

    my_file = open(file_name, 'r')
    finished_flag = False
    counter = 0
    while(not finished_flag):
        line = my_file.readline()
        if not line:
            finished_flag = True
        else:
            if line.find('ranges: [') != -1:
                counter = counter + 1
                print('Scan #{}\nPoints generated: {}'.format\
                    (counter,len(count_points(line))))
    my_file.close()
    if(counter == 0):
        print('Not found')

def count_points(string):
    #print(string)
    start_index = string.find('[')
    end_index = string.find(']')
    points = string[start_index:end_index].split(',')
    return points

if __name__ == '__main__':
    main()
